services:
  frontend:
    image: node:22-bookworm
    working_dir: /app
    volumes:
      - ./frontend:/app
      # - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0
  backend:
    image: node:22-bookworm
    working_dir: /app
    volumes:
      - ./backend:/app
      # - backend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      DATABASE_URL: postgresql://collabz:collabz@db:5432/collabz
    depends_on:
      - db
    env_file:
      - ./backend/.env

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: collabz
      POSTGRES_PASSWORD: collabz
      POSTGRES_DB: collabz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  # frontend_node_modules:
  # backend_node_modules:
  postgres_data:
